FROM debian:stretch
#FROM ruby
MAINTAINER FAMBRANDS

EXPOSE 5678

# Install wget, sox and flite
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ruby ruby-dev zlib1g-dev build-essential && \
    gem install resque-web

WORKDIR /data

CMD ["resque-web", "-FL", "-r", "$REDIS_URL"]
